version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # test
 - run: |
        docker build -t adbms-site .
#        docker run -p 80:80 adbms-site
        docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web
